<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2019-06-20
 * Time: 22:30
 */

namespace app\common\command;


use think\console\Command;
use think\console\Input;
use think\console\Output;

class MigrateCommand extends Command
{
    protected function configure()
    {
        $this->setName('db:migrate')
            ->setDescription('database migrate command !');
    }

    protected function execute(Input $input, Output $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}